// 스킬 카테고리 타이틀
export const SKILL_CATEGORIES = ['디자인', '개발', '기획', '마케팅', '기타'] as const

export type SkillCategory = (typeof SKILL_CATEGORIES)[number]

// 카테고리별 스킬 목록
export const SKILLS_BY_CATEGORY: Record<SkillCategory, string[]> = {
	디자인: [
		'Figma',
		'Photoshop',
		'Illustrator',
		'Premiere Pro',
		'After Effect',
		'Adobe Firefly',
		'Mdjourney',
		'Nano Banana',
		'DALL.E',
		'Blender',
		'Cinema 4d',
		'VFX',
		'MAYA',
		'ZBrush',
		'Sketch up',
		'Auto CAD',
		'3D Max',
		'Rhino',
		'Keyshot',
		'Procreate',
		'Enscape',
	],
	개발: [
		'Java',
		'HTML/CSS',
		'JavaScript',
		'TypeScript',
		'Python',
		'React',
		'Spring',
		'Spring Boot',
		'Node.js',
		'Vue.js',
		'Next.js',
		'Docker',
		'AWS',
		'MySQL',
		'GO',
		'C#',
		'Swift',
		'Android Studio',
		'Kotlin',
		'Flutter',
		'React Native',
		'PostgreSQL',
		'C++',
		'JSP',
		'Git',
		'GitHub',
		'Kubernetes',
	],
	기획: ['Notion', 'Ux Research', 'Slack', 'Jira', 'Confluence', 'Balsamiq', 'Miro', 'Google Analytics', 'Amplitude', 'Excel'],
	마케팅: [
		'Google Tag Manager',
		'AppsFlyer',
		'Meta Ads Manager',
		'Google Ads',
		'Kakao Moment',
		'Canve',
		'Braze',
		'Solapi',
		'Mailchimp',
	],
	기타: [
		'Chat GPT',
		'Trados',
		'Live Streaming',
		'Google Gemini',
		'Memsource',
		'VMD',
		'Claude',
		'Consecutive Interpretation',
		'3D Rendering',
		'Google Workspace',
		'Pro Tools',
		'Safety Management',
		'Canva',
		'Logic Pro',
		'Power BI',
		'Miricanvas',
		'Ableton Live',
		'CRM Setup',
		'Channel Talk',
		'iZotope RX',
		'CapCut',
		'DaVinci Resolve',
		'Vrew',
		'Storyboarding',
		'DeepL',
		'Drone Piloting',
	],
}

// 모든 스킬 목록
export const ALL_SKILLS = Object.values(SKILLS_BY_CATEGORY).flat()
