// Role ID에 따른 순환 색상 (1-7 순환)
const ROLE_COLORS = [
	'bg-roletag-purple', // 1, 8, 15...
	'bg-roletag-pink', // 2, 9, 16...
	'bg-roletag-green', // 3, 10, 17...
	'bg-roletag-blue', // 4, 11, 18...
	'bg-roletag-yellow', // 5, 12, 19...
	'bg-roletag-orange', // 6, 13, 20...
	'bg-roletag-gray', // 7, 14, 21...
]

export const getRoleColorById = (id: number): string => {
	const index = (id - 1) % ROLE_COLORS.length
	return ROLE_COLORS[index]
}

export default ROLE_COLORS
